---
name: Terraform
description: Terraform all-in-one workflow
inputs:
  google_credentials:
    required: false
    description: Google credentials
  terraform_directory:
    required: false
    description: Location of terraform manifests
    default: ./
  terraform_do_apply:
    required: false
    description: Whether to run `terraform apply` as last step
    default: 'false'
runs:
  using: node12
  main: dist/index.js
