---
name: Terraform
description: Terraform all-in-one workflow
inputs:
  google_credentials:
    required: true
    description: Google credentials
  terraform_directory:
    required: false
    description: Location of terraform manifests
    default: ./
  terraform_do_apply:
    required: false
    description: Whether to run `terraform apply` as last step
    default: 'false'
  terraform_lock:
    required: false
    description: Whether to (try to) lock the state during plan/apply
    default: 'false'
  terraform_parallelism:
    required: false
    description: Limit the number of concurrent operations during plan/apply
    default: '10'
runs:
  # node16 not available
  # https://github.com/actions/runner/issues/772
  using: docker
  image: Dockerfile
