---
name: Continuous Integration

on:
  pull_request:

jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: make install

    - name: Run code style test
      run: make cs

  check-dist:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: make install

    - name: Rebuild the dist/ directory
      run: make build

    - name: Compare the expected and actual dist/ directories
      run: |
        git diff --quiet --ignore-space-at-eol dist/ && exit 0
        echo "Detected uncommitted changes after build.  See status below:"
        git diff --exit-code dist/
      id: diff

    # If index.js was different than expected, upload the expected version as an artifact
    #- uses: actions/upload-artifact@v2
    #  if: ${{ failure() && steps.diff.conclusion == 'failure' }}
    #  with:
    #    name: dist
    #    path: dist/

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: make install

    - name: Run code style test
      run: make test
